export const data = [
  {
    name: "Tomodev",
    description: "web development agency.",
    techStack: [
      "Next.js",
      "React",
      "Node.js",
      "TypeScript",
      "Tailwind CSS",
      "magicUI",
      "GSAP",
    ],
    imgurl: "/tomodev.png",
    repo: "https://github.com/redaAssemghor/tomodev",
    deployUrl: "https://tomodev.vercel.app/",
  },
  {
    name: "PicGen",
    description: "AI-powered text-to-image generation.",
    techStack: [
      "Openai",
      "Stable Diffusion",
      "Next.js",
      "Stripe",
      "Clerk",
      "TailwindCSS",
      "GSAP",
      "Prisma",
      "MongoDB",
      "reduxjs toolkit",
      "Typescript",
    ],
    imgurl: "/picgen.png",
    repo: "https://github.com/redaAssemghor/picGen",
    deployUrl: "https://pic-gen-lilac.vercel.app/",
  },
  {
    name: "PDF to MP3 Generator",
    description: "Convert text and PDFs into audio with a sleek UI.",
    techStack: [
      "Next.js",
      "React",
      "Clerk",
      "Convex",
      "Tailwind CSS",
      "GSAP",
      "PDF.js",
    ],
    imgurl: "/pdftomp3.png",
    repo: "https://github.com/redaAssemghor/pdf-to-mp3",
    deployUrl: "https://pdf-to-mp3-amber.vercel.app/",
  },
  {
    name: "Solar System 3D Simulator",
    description: "Explore the solar system with realistic 3D graphics.",
    techStack: ["React", "Three.js", "Tailwind CSS"],
    imgurl: "/solar-system.png",
    repo: "https://github.com/redaAssemghor/3D-solar-system",
    deployUrl: "https://3-d-solar-system-rho.vercel.app/",
  },
  {
    name: "SoundWave",
    description: "Transform audio into immersive 3D animations.",
    techStack: ["Next.js", "React Three Fiber", "Tailwind CSS"],
    imgurl: "/sound-wave.png",
    repo: "https://github.com/redaAssemghor/sound-wave",
    deployUrl: "https://sound-wave.vercel.app/",
  },
  {
    name: "Micro Saas Finder",
    description: "Generate Micro SaaS ideas using AI.",
    techStack: ["Next.js", "React", "Tailwind CSS", "Clerk", "Convex"],
    imgurl: "/saas-finder.png",
    repo: "https://github.com/redaAssemghor/micro-saas-finder",
    deployUrl: "https://micro-saas-finder.vercel.app",
  },
  // {
  //   name: "payloadcms Ecommerce template",
  //   description: "E-commerce template with secure authentication.",
  //   techStack: ["Next.js", "TypeScript", "MongoDB", "Stripe"],
  //   imgurl: "/payloadcms.png",
  //   repo: "https://github.com/redaAssemghor/payload-commerce",
  //   deployUrl: "",
  // },
  // {
  //   name: "MyShopee",
  //   description: "Next.js 13 e-commerce with advanced admin features.",
  //   techStack: ["Next.js", "TypeScript", "Tailwind CSS", "Prisma", "DaisyUI"],
  //   imgurl: "/myshopee.png",
  //   repo: "https://github.com/redaAssemghor/myCommerce",
  //   deployUrl: "https://my-shopee-ashen.vercel.app/",
  // },
];
